---
repository:
  description: Template for TypeScript & NodeJS
  topics: vscode, codespaces, devcontainer, typescript, javascript, npm, node, nodejs
  delete_branch_on_merge: true
  has_wiki: false
  # private: false
